export const COLUMN_MAPS: Record<string, string[]> = {
  name: [
    'name','product name','style name','item name','product title','style title','item title',
    'style','title','article name','line name','range name','product ref','style desc',
    'designation','item','product','title & pictures','article','style description',
    'product header','style header','collection piece','product label','style label',
    'garment name','item label',
    'désignation','nom produit','nom du produit','libellé','libelle','intitulé','intitule','nom article',
    'denominazione','nome prodotto','nome articolo','bezeichnung','produktname','artikelname',
    'nombre producto','nombre artículo','nombre articulo','display name','product handle',
  ],
  description: [
    'description','product description','long description','full description','item description',
    'article description','item details','product details','product copy','marketing copy',
    'copy','style notes','additional info','specifications','spec','desc','description text',
    'product info','item info','detail','details','item detail','product detail','style detail',
    'line detail','article detail','garment detail',
    'description produit','description article','détail','detail produit','détails','détail produit',
    'descrizione','descrizione prodotto','beschreibung','produktbeschreibung',
  ],
  sku: [
    'sku','style #','style no','style number','item code','item #','item no','item number',
    'item num','vendor code','vendor #','vendor no','vendor id','article no','article number',
    'article #','ref','ref #','ref no','reference','barcode','upc','ean','product code',
    'product id','style code','style id','code','part no','part number','part #','model',
    'model no','model number','model #','catalog no','catalog #','cat no','prod code',
    'internal code','internal ref','brand code','supplier code','supplier ref','factory code',
    'factory ref','merchant sku','seller sku','parent sku','variant sku','sku #','sku no',
    'style ref','item ref','season code ref','product number','prod no','prod #','product no',
    'variant sku','shopify sku','handle','variant barcode',
    'référence','réf','ref article','code article','code produit','num article',
    'codice','codice articolo','codice prodotto','cod articolo',
    'artikelnummer','artikel nr','artikel-nr','código','codigo','referencia',
  ],
  color: [
    'color','colour','colorway','colourway','clrwy','vendor color','vendor colour',
    'color name','colour name','col','colourway name','colour description','color description',
    'color/style','color code','colour code','color ref','colour ref','shade','hue','tone',
    'colorname','colour way','color way','finish','dye lot','color option','colour option',
    'fabric color','fabric colour','clr','coloris','couleur','colore','colorazione',
    'farbe','farbvariante','color name & code','color & code',
  ],
  gender: [
    'gender','sex','mens','womens','men','women','boys','girls','male','female','unisex',
    'target gender','gendered','gender category','audience','gender group','customer gender',
    'market','gender market','genre','sexe','genere','sesso','geschlecht',
    'demographic','target market','intended for',
  ],
  season: [
    'season','collection','drop','season/collection','collection name','range','season code',
    'collection code','launch date','release date','program','theme','assortment','line',
    'product line','saison','gamme','collection nom','stagione','collezione','kollektion',
  ],
  brand_name: [
    'brand','brand name','supplier','supplier name','vendor','vendor name','manufacturer',
    'label','label name','maker','producer','marque','marca','marke',
  ],
  material: [
    'material','fabric','composition','content','fiber','fibre','fabric content',
    'material composition','textile','blend','fabric composition','material content',
    'fiber content','fibre content','yarn','yarn content','construction','fabric type',
    'material type','raw material','fabric detail','care label','washing','fabric & care',
    'material & care','care instructions','care info','shell','lining','outer shell',
    'outer material','inner lining','fill','fill power','down content',
    'matière','matiere','composition matière','tissu','confection','matières','matieres',
    'materiale','composizione','tessuto','stoff','zusammensetzung','composición','composicion','tejido',
  ],
  delivery_window: [
    'delivery window','delivery period','ship window','ship dates','delivery dates',
    'expected delivery','delivery schedule','arrival window','ex works window',
    'ex works dates','exw window','estimated delivery','lead time','shipping window',
    'delivery','ship date','shipping date','dispatch date','ex works date','exw date',
    'arrival date','avail date','available date','in store date','in-store date',
    'delivery month','ship month','ex works','exw',
    'livraison','date livraison','délai livraison','délai de livraison',
    'consegna','data consegna','lieferung','lieferdatum','liefertermin',
  ],
  wsp_usd: [
    'wholesale','wsp','wholesale price','vendor wsp','vendor wsp usd','ws price','wsp usd',
    'wsp_usd','b2b price','b2b','trade price','net price','buy price','wholesale usd',
    'selling price to buyer','buyer price','dealer price','distributor price','reseller price',
    'purchase price','net net','ex factory','ex-factory','exf','fob price','landed price',
    'base price','floor price',
    'wholesale (usd)','wholesale (eur)','wholesale (gbp)','wholesale (chf)','wholesale (aud)',
    'wholesale (cad)','wholesale (hkd)','wholesale (jpy)','wsp (usd)','wsp (eur)','wsp (gbp)',
    'wsp (chf)','trade price (usd)','trade price (eur)','trade price (gbp)','b2b price usd',
    'b2b price eur','net usd','net eur',
    'prix grossiste','prix achat','prix de vente grossiste','prix net','prix ht','tarif grossiste',
    'prezzo ingrosso','prezzo netto','prezzo b2b',
    'einkaufspreis','händlerpreis','nettopries','grosshandel preis',
    'precio mayorista','precio neto',
  ],
  srp: [
    'retail','retail price','msrp','srp','tag price','rrp','suggested retail','retail usd',
    'consumer price','public price','rsp','recommended retail','recommended price',
    'market price','end price','consumer retail','srp usd','retail srp','full price','listed price',
    'retail price (usd)','retail price (eur)','retail price (gbp)','retail price (chf)',
    'retail price (aud)','retail price (cad)','retail price (hkd)','retail price (jpy)',
    'rrp (gbp)','rrp (usd)','rrp (eur)','msrp (usd)','srp (usd)','srp (eur)','srp (chf)',
    'consumer price (usd)','consumer price (eur)',
    'prix public','prix conseillé','prix conseillee','prix de vente conseillé','prix client',
    'prix ttc','pvp',
    'prezzo pubblico','prezzo consigliato','prezzo retail',
    'verkaufspreis','empfohlener verkaufspreis','uvp','verbraucherpreis',
    'precio público','precio publico',
  ],
  price_combined: [
    'wsp/srp','wholesale/retail','cost/retail','price (wsp/srp)','wsp / srp',
    'wholesale / retail','wsp & srp',
  ],
  cost: [
    'cost','cogs','cost of goods','landed cost','unit cost','buy cost','production cost',
    'factory cost','manufacturing cost','cog','cost of goods sold','fob cost',
    'ex factory cost','first cost','sample cost','bom cost',
    'prix revient','coût','cout','prix de revient','costo','costo produzione',
    'kosten','herstellungskosten','einstandspreis',
  ],
  stock_total: [
    'inventory','stock','available','on hand','total quantity','units','pcs',
    'pieces available','available units','units available','total pcs','total pieces',
    'total units','sum','total stock','qty total','quantity total','stock level',
    'current stock','available stock','in stock','inventory level','warehouse qty',
    'available qty','remaining qty','balance qty',
    'stock disponible','quantité disponible','disponible',
    'quantità disponibile','disponibile','bestand','verfügbar','lagerbestand',
  ],
  moq: [
    'minimum','moq','min order','order minimum','min qty','minimum qty',
    'minimum order quantity','min order qty','min units','minimum units','order min',
    'minimum order','minimum pieces','min pcs','min pieces','piece minimum',
    'unit minimum','pack size','pack qty','set qty','assortment minimum','min assortment',
    'minimum commande','qté minimum','quantité minimum',
    'quantità minima','minimo ordine','mindestbestellmenge','mindest menge',
  ],
  category: [
    'dept','department','type','category','class','product type','category lv1','category lv2',
    'category level 2','category level2','cat lv2','cat','product category','garment type',
    'item type','product class','product group','division','sub category','subcategory',
    'item category','merchandise type','classification','apparel type','style type',
    'group','product line','lv1','lv2','level 1','level 2','cat level 1','cat level 2',
    'shopify type','product type (shopify)','google category',
    'catégorie','categorie','famille','rayon','categoria','reparto',
    'kategorie','warengruppe','abteilung','categoría',
  ],
  product_notes: [
    'notes','product notes','style notes','item notes','additional info','additional notes',
    'remarks','comments','memo','info','extra info','other info','internal notes',
    'buyer notes','import notes','custom field','misc','miscellaneous',
    'remarques','observations','commentaires','note','osservazioni',
    'notizen','anmerkungen','bemerkungen',
  ],
  size_range: [
    'size','sizes','size range','size run','available sizes','size availability',
    'size chart','sizing','size grid','size options','size breakdown','size spread',
    'size listing','size set','run of sizes','size group',
  ],
  // Individual size cols — exact only
  size_xxs:['xxs','xx-small','xxsmall','2xs'],
  size_xs:['xs','x-small','xsmall'],
  size_s:['s','small','size s','sz s','sm'],
  size_m:['m','medium','med','size m','sz m'],
  size_l:['l','large','size l','sz l','lg'],
  size_xl:['xl','x-large','xlarge','size xl','sz xl'],
  size_xxl:['xxl','xx-large','xxlarge','2xl','size xxl','sz xxl'],
  size_xxxl:['xxxl','3xl','xxx-large','size xxxl'],
  size_4xl:['4xl','xxxxl','4x-large','xxxx-large'],
  size_5xl:['5xl','xxxxxl','5x-large'],
  size_6xl:['6xl','6x-large'],
  size_7xl:['7xl'],
  size_8xl:['8xl'],
  size_1x:['1x'], size_2x:['2x'], size_3x:['3x'], size_4x:['4x'], size_5x:['5x'],
  size_2t:['2t'], size_3t:['3t'], size_4t:['4t'], size_5t:['5t'], size_6t:['6t'],
  size_nb:['nb','newborn','new born','preemie','0m'],
  size_0_3m:['0-3m','0/3m','0/3'], size_3_6m:['3-6m','3/6m','3/6'],
  size_6_9m:['6-9m','6/9m','6/9'], size_9_12m:['9-12m','9/12m','9/12'],
  size_12_18m:['12-18m','12/18m','12/18'], size_18_24m:['18-24m','18/24m','18/24','24m'],
  size_30:['30'],size_32:['32'],size_34:['34'],size_35:['35'],size_36:['36'],size_37:['37'],
  size_38:['38'],size_39:['39'],size_40:['40'],size_41:['41'],size_42:['42'],size_43:['43'],
  size_44:['44'],size_46:['46'],size_48:['48'],size_50:['50'],size_52:['52'],size_54:['54'],
  size_26:['26'],size_27:['27'],size_29:['29'],size_31:['31'],size_33:['33'],
  size_7:['7'],size_8:['8'],size_9:['9'],size_10:['10'],size_11:['11'],size_12:['12'],size_13:['13'],
  size_16:['16'],size_18:['18'],size_20:['20'],size_22:['22'],size_24:['24'],
  size_45:['45'],size_47:['47'],size_49:['49'],
  size_6_5:['6.5','6½'],size_7_5:['7.5','7½'],size_8_5:['8.5','8½'],
  size_9_5:['9.5','9½'],size_10_5:['10.5','10½'],size_11_5:['11.5','11½'],
  size_80:['80'],size_86:['86'],size_92:['92'],size_98:['98'],
  size_104:['104'],size_110:['110'],size_116:['116'],size_122:['122'],
  size_128:['128'],size_134:['134'],size_140:['140'],size_146:['146'],
  size_152:['152'],size_158:['158'],size_164:['164'],size_170:['170'],
  size_1:['1'],size_2:['2'],size_3:['3'],size_4:['4'],size_5:['5'],size_6:['6'],
  size_os:['os','one size','onesize','o/s','free size','freesize','one-size','universal'],
  wsp_tier_high: [
    'wholesale tier high - below moq','wholesale tier high — below moq','wholesale tier high',
    'wsp tier high','wsp tier high - below moq','wholesale 40%','wsp 40%','above moq',
    'wsp above moq','wsp high','standard wsp','regular wsp','single unit','below moq wsp',
    'standard wholesale','single wsp',
  ],
  wsp_tier_low: [
    'wholesale tier low - bulk/moq+','wholesale tier low — bulk/moq+','wholesale tier low',
    'wsp tier low','wsp tier low - bulk/moq+','wholesale 35%','wsp 35%','below moq',
    'wsp below moq','wsp low','bulk wsp','moq wsp','above moq wsp','volume wsp',
    'wsp moq+','bulk wholesale','volume wholesale','moq wholesale',
  ],
  carton_id: [
    'your carton #','carton #','carton id','carton number','box #','box id','carton',
    'box number','ctn #','ctn no','carton no','packing unit','shipping unit',
  ],
  dimensions: [
    'dimensions','dim','size (cm)','box size','carton size','measurement','l*w*h','lwh',
    'dimension','carton dimensions','package size','box dimensions',
  ],
  weight: [
    'weight','wt','gross weight','net weight','kg','weight (kg)','carton weight',
    'gw','nw','g.w.','n.w.','gross wt','net wt','unit weight','item weight',
  ],
  location: [
    'location','warehouse','origin','ship from','origin country','warehouse location',
    'country of origin','coo','made in','manufactured in','production country','source',
  ],
  image_url: [
    'image','image url','photo','photo url','picture','picture url','img','img url',
    'thumbnail','product image','product photo','image 1','image 2','image 3','image 4',
    'image 5','image one','image two','image three','image four','image five',
    'image_1','image_2','image_3','image_4','photo 1','photo 2','photo 3',
    'front image','back image','detail image','main image','hero image','cover image',
    'image link','photo link','image_url','img_url',
  ],
  showroom_city: [
    'showroom','city','showroom city','event city','location','drop hub',
    'venue','hub','market','trade show','fair','event location',
    'show location','tradeshow','trade fair','market location',
    'event','show','fashion week','fw location',
  ],
};

export const ANTIDOTE_SIZE_FIELDS: Record<string, string> = {
  size_xxs:'XXS', size_xs:'XS', size_s:'S', size_m:'M', size_l:'L',
  size_xl:'XL', size_xxl:'XXL', size_xxxl:'XXXL',
  size_4xl:'4XL', size_5xl:'5XL', size_6xl:'6XL', size_7xl:'7XL', size_8xl:'8XL',
  size_os:'OS',
  size_1x:'1X', size_2x:'2X', size_3x:'3X', size_4x:'4X', size_5x:'5X',
  size_2t:'2T', size_3t:'3T', size_4t:'4T', size_5t:'5T', size_6t:'6T',
  size_nb:'NB', size_0_3m:'0-3M', size_3_6m:'3-6M', size_6_9m:'6-9M',
  size_9_12m:'9-12M', size_12_18m:'12-18M', size_18_24m:'18-24M',
  size_30:'30', size_32:'32', size_34:'34', size_35:'35', size_36:'36',
  size_37:'37', size_38:'38', size_39:'39', size_40:'40', size_41:'41',
  size_42:'42', size_43:'43', size_44:'44', size_46:'46', size_48:'48',
  size_50:'50', size_52:'52', size_54:'54',
  size_26:'26', size_27:'27', size_29:'29', size_31:'31', size_33:'33',
  size_7:'7', size_8:'8', size_9:'9', size_10:'10', size_11:'11',
  size_12:'12', size_13:'13', size_16:'16', size_18:'18', size_20:'20',
  size_22:'22', size_24:'24', size_45:'45', size_47:'47', size_49:'49',
  size_6_5:'6.5', size_7_5:'7.5', size_8_5:'8.5', size_9_5:'9.5',
  size_10_5:'10.5', size_11_5:'11.5',
  size_80:'80', size_86:'86', size_92:'92', size_98:'98',
  size_104:'104', size_110:'110', size_116:'116', size_122:'122',
  size_128:'128', size_134:'134', size_140:'140', size_146:'146',
  size_152:'152', size_158:'158', size_164:'164', size_170:'170',
  size_1:'1', size_2:'2', size_3:'3', size_4:'4', size_5:'5', size_6:'6',
};

export const EXACT_ONLY_COLS = new Set([
  'size_xxs','size_xs','size_s','size_m','size_l','size_xl','size_xxl','size_xxxl','size_os',
  'size_4xl','size_5xl','size_6xl','size_7xl','size_8xl',
  'size_1x','size_2x','size_3x','size_4x','size_5x',
  'size_2t','size_3t','size_4t','size_5t','size_6t',
  'size_nb','size_0_3m','size_3_6m','size_6_9m','size_9_12m','size_12_18m','size_18_24m',
  'size_30','size_32','size_34','size_35','size_36','size_37','size_38','size_39','size_40',
  'size_41','size_42','size_43','size_44','size_46','size_48','size_50','size_52','size_54',
  'size_26','size_27','size_29','size_31','size_33',
  'size_7','size_8','size_9','size_10','size_11','size_12','size_13',
  'size_16','size_18','size_20','size_22','size_24',
  'size_45','size_47','size_49',
  'size_6_5','size_7_5','size_8_5','size_9_5','size_10_5','size_11_5',
  'size_80','size_86','size_92','size_98',
  'size_104','size_110','size_116','size_122',
  'size_128','size_134','size_140','size_146',
  'size_152','size_158','size_164','size_170',
  'size_1','size_2','size_3','size_4','size_5','size_6',
]);

export const KEYWORD_FINGERPRINTS: Record<string, string[]> = {
  name:['style name','style desc','product name','item name','article name','product title','style title','designation'],
  description:['product description','long description','product copy','marketing copy','item details','product details','product info','style notes','full description'],
  sku:['sku','style no','style #','item code','article no','vendor code','barcode','upc','product code','style code','supplier code'],
  category:['category','dept','garment type','product type','item type','lv1','lv2','level 1','level 2'],
  color:['color','colour','colorway','colourway','shade','color option','colour option','coloris','couleur','colore','farbe'],
  season:['season','collection','drop','season code','program','collection name'],
  brand_name:['brand name','supplier name','vendor name','label name','manufacturer'],
  material:['material','fabric','composition','content','fiber','fibre','fabric content','textile'],
  delivery_window:['delivery window','ship window','delivery period','ship date','ex works','available date'],
  wsp_usd:['wsp','wholesale','vendor wsp','b2b price','trade price','buy price','net price','wholesale price'],
  srp:['srp','msrp','rrp','retail','retail price','consumer price','public price','full price','recommended price'],
  stock_total:['stock','inventory','available','units','on hand','stock level','in stock'],
  moq:['moq','minimum','min order','min qty','order minimum','piece minimum'],
  cost:['cogs','cost of goods','landed cost','factory cost','production cost'],
  size_range:['size run','size range','available sizes','size chart','sizing'],
  weight:['weight','gross weight','net weight'],
  dimensions:['dimensions','carton size','box size'],
  image_url:['image','photo','picture','thumbnail'],
  product_notes:['notes','remarks','comments','additional info','internal notes'],
};

export const ABBREV_EXPANSIONS: Record<string, string> = {
  qty:'quantity', pcs:'pieces', pc:'pieces', desc:'description', prod:'product',
  cat:'category', col:'color', clr:'color', sz:'size', wt:'weight',
  wsp:'wholesale', srp:'retail price', msrp:'retail price', rrp:'retail price',
  pvp:'retail price', uvp:'retail price', avail:'available', inv:'inventory',
  usd:'', eur:'', gbp:'', chf:'', cad:'', aud:'', hkd:'',
  lv1:'level 1', lv2:'level 2', lv3:'level 3', no:'number', ref:'reference',
  std:'standard', min:'minimum', max:'maximum', tot:'total', sub:'subtotal',
  moq:'minimum order quantity', cogs:'cost of goods sold',
  b2b:'business to business wholesale', qte:'quantity',
};
